arch: mobilenet # MobileNet V1
widen_factor: 1.0
checkpoint_fp: ./TDDFA_V2/weights/mb1_120x120.pth
bfm_fp: ./TDDFA_V2/configs/bfm_noneck_v3.pkl # or ./TDDFA_V2/configs/bfm_noneck_v3_slim.pkl
size: 120
num_params: 62
